@startuml trainingplan_use_case_diagram

left to right direction

actor Supervisor as User

rectangle "Training Plan" {
  usecase UC1 as "Navigate to Task Monitoring Page"
  usecase "Display Created Training Plans" as UC2
  usecase "Create Training Plan" as UC3
  usecase "Display Create Training Plan Modal" as UC4
  usecase "Enter Training Plan Information" as UC5
  usecase "Display Submission Response" as UC6
  usecase "Close Modal" as UC7
  usecase "Assign Training Plan" as UC8
}
User -- UC1
UC1 ..> UC2 : <<include>>
User -- UC3
UC3 ..> UC4 : <<include>>
User -- UC5
UC5 <.. UC6 : <<extend>>
UC5 <.. UC7 : <<extend>>
User -- UC8
UC8 <.. UC6 : <<extend>>

@enduml
